modLoader="javafml"
loaderVersion="[43,)"
license="Attribution-NonCommercial-ShareAlike 3.0 Unported"
issueTrackerURL="https://github.com/ChorusTeam/ChorusLib/issues"
[[mods]]
modId="chorus_lib"
version="${file.jarVersion}"
displayName="ChorusLib"
displayURL="https://github.com/ChorusTeam/ChorusLib"
logoFile="icon.png"
authors="YeoXuHang"
description='''
A library mod for Chorus Team
'''
[[dependencies.chorus_lib]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.chorus_lib]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"