accessWidener	v1	named
accessible	class	net/minecraft/world/level/biome/Biome$ClimateSettings
accessible	field	net/minecraft/world/level/biome/MultiNoiseBiomeSource	preset	Ljava/util/Optional;
accessible	class	net/minecraft/world/level/biome/MultiNoiseBiomeSource$PresetInstance
accessible	field	net/minecraft/world/level/biome/MultiNoiseBiomeSource$Preset	parameterSource	Ljava/util/function/Function;
accessible	field	net/minecraft/world/level/biome/MultiNoiseBiomeSource	parameters	Lnet/minecraft/world/level/biome/Climate$ParameterList;
mutable	field	net/minecraft/world/level/biome/MultiNoiseBiomeSource	parameters	Lnet/minecraft/world/level/biome/Climate$ParameterList;
accessible	field	net/minecraft/world/level/biome/BiomeSource	possibleBiomes	Ljava/util/Set;
mutable	field	net/minecraft/world/level/biome/BiomeSource	possibleBiomes	Ljava/util/Set;
accessible	field	net/minecraft/world/level/biome/Biome	climateSettings	Lnet/minecraft/world/level/biome/Biome$ClimateSettings;
accessible	field	net/minecraft/world/level/biome/Biome	generationSettings	Lnet/minecraft/world/level/biome/BiomeGenerationSettings;
accessible	field	net/minecraft/world/level/biome/Biome	mobSettings	Lnet/minecraft/world/level/biome/MobSpawnSettings;
accessible	field	net/minecraft/world/level/biome/Biome$ClimateSettings	precipitation	Lnet/minecraft/world/level/biome/Biome$Precipitation;
mutable	field	net/minecraft/world/level/biome/Biome$ClimateSettings	precipitation	Lnet/minecraft/world/level/biome/Biome$Precipitation;
accessible	field	net/minecraft/world/level/biome/Biome$ClimateSettings	temperature	F
mutable	field	net/minecraft/world/level/biome/Biome$ClimateSettings	temperature	F
accessible	field	net/minecraft/world/level/biome/Biome$ClimateSettings	temperatureModifier	Lnet/minecraft/world/level/biome/Biome$TemperatureModifier;
mutable	field	net/minecraft/world/level/biome/Biome$ClimateSettings	temperatureModifier	Lnet/minecraft/world/level/biome/Biome$TemperatureModifier;
accessible	field	net/minecraft/world/level/biome/Biome$ClimateSettings	downfall	F
mutable	field	net/minecraft/world/level/biome/Biome$ClimateSettings	downfall	F
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	fogColor	I
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	fogColor	I
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	waterColor	I
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	waterColor	I
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	waterFogColor	I
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	waterFogColor	I
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	skyColor	I
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	skyColor	I
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	foliageColorOverride	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	foliageColorOverride	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	grassColorOverride	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	grassColorOverride	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	grassColorModifier	Lnet/minecraft/world/level/biome/BiomeSpecialEffects$GrassColorModifier;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	grassColorModifier	Lnet/minecraft/world/level/biome/BiomeSpecialEffects$GrassColorModifier;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientParticleSettings	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientParticleSettings	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientLoopSoundEvent	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientLoopSoundEvent	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientMoodSettings	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientMoodSettings	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientAdditionsSettings	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	ambientAdditionsSettings	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/BiomeSpecialEffects	backgroundMusic	Ljava/util/Optional;
mutable	field	net/minecraft/world/level/biome/BiomeSpecialEffects	backgroundMusic	Ljava/util/Optional;
accessible	field	net/minecraft/world/level/biome/MobSpawnSettings	creatureGenerationProbability	F
mutable	field	net/minecraft/world/level/biome/MobSpawnSettings	creatureGenerationProbability	F
accessible	field	net/minecraft/world/level/biome/MobSpawnSettings	spawners	Ljava/util/Map;
mutable	field	net/minecraft/world/level/biome/MobSpawnSettings	spawners	Ljava/util/Map;
accessible	field	net/minecraft/world/level/biome/MobSpawnSettings	mobSpawnCosts	Ljava/util/Map;
mutable	field	net/minecraft/world/level/biome/MobSpawnSettings	mobSpawnCosts	Ljava/util/Map;
accessible	method	net/minecraft/world/level/biome/MobSpawnSettings$MobSpawnCost	<init>	(DD)V
accessible	field	net/minecraft/world/level/biome/BiomeGenerationSettings	carvers	Ljava/util/Map;
mutable	field	net/minecraft/world/level/biome/BiomeGenerationSettings	carvers	Ljava/util/Map;
accessible	field	net/minecraft/world/level/biome/BiomeGenerationSettings	features	Ljava/util/List;
mutable	field	net/minecraft/world/level/biome/BiomeGenerationSettings	features	Ljava/util/List;
accessible	field	net/minecraft/world/level/biome/BiomeGenerationSettings	flowerFeatures	Ljava/util/function/Supplier;
mutable	field	net/minecraft/world/level/biome/BiomeGenerationSettings	flowerFeatures	Ljava/util/function/Supplier;
accessible	field	net/minecraft/world/level/biome/BiomeGenerationSettings	featureSet	Ljava/util/function/Supplier;
mutable	field	net/minecraft/world/level/biome/BiomeGenerationSettings	featureSet	Ljava/util/function/Supplier;
accessible method net/minecraft/world/level/block/NyliumBlock canBeNylium (Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/LevelReader;Lnet/minecraft/core/BlockPos;)Z
